In [1]:
import pandas as pd

In [11]:
df = pd.read_csv("kakeibo2025.csv")
df.head()

           日付 カテゴリ     金額       メモ
0  2025-01-01  住宅費  97238       家賃
1  2025-01-01  交通費   1573    ガソリン代
2  2025-01-02  交通費    830    出張交通費
3  2025-01-03   娯楽   3969      飲み会
4  2025-01-03   食費   2597  お弁当と飲み物

In [6]:
df.sort_values(by="金額")

             日付 カテゴリ     金額      メモ
477  2025-12-13  交通費    250   ガソリン代
319  2025-08-29  交通費    290    駐車場代
489  2025-12-25  交通費    294   出張交通費
397  2025-10-19  交通費    324   ガソリン代
260  2025-07-13  日用品    328  生活雑貨購入
..          ...  ...    ...     ...
31   2025-02-01  住宅費  95000      家賃
73   2025-03-01  住宅費  95000      家賃
415  2025-11-01  住宅費  95000      家賃
111  2025-04-01  住宅費  95000      家賃
0    2025-01-01  住宅費  95000      家賃

[500 rows x 4 columns]

In [7]:
df[df["カテゴリ"] == "住宅費"]

             日付 カテゴリ     金額  メモ
0    2025-01-01  住宅費  95000  家賃
31   2025-02-01  住宅費  95000  家賃
73   2025-03-01  住宅費  95000  家賃
111  2025-04-01  住宅費  95000  家賃
147  2025-05-01  住宅費  95000  家賃
196  2025-06-01  住宅費  95000  家賃
242  2025-07-01  住宅費  95000  家賃
275  2025-08-01  住宅費  95000  家賃
325  2025-09-01  住宅費  95000  家賃
363  2025-10-01  住宅費  95000  家賃
415  2025-11-01  住宅費  95000  家賃
462  2025-12-01  住宅費  95000  家賃

In [12]:
df.groupby("カテゴリ")["金額"].sum()

カテゴリ
その他      20413
交通費      60678
交際費     199996
住宅費    1130321
光熱費     585416
医療費     183500
娯楽      206326
教育費      80326
日用品     149837
食費      218574
Name: 金額, dtype: int64

In [13]:
df[df["カテゴリ"] == "教育費"]

             日付 カテゴリ    金額     メモ
17   2025-01-15  教育費  5756  通信講座費
47   2025-02-15  教育費  6426  通信講座費
84   2025-03-15  教育費  6214  通信講座費
126  2025-04-15  教育費  5719  通信講座費
169  2025-05-15  教育費  7533  通信講座費
218  2025-06-15  教育費  7718  通信講座費
261  2025-07-15  教育費  5430  通信講座費
311  2025-08-15  教育費  5683  通信講座費
362  2025-09-15  教育費  6252  通信講座費
403  2025-10-15  教育費  7765  通信講座費
445  2025-11-15  教育費  7598  通信講座費
481  2025-12-15  教育費  8232  通信講座費